TL_PARSER_OBJECTS=${OBJ}/tl-parser.o ${OBJ}/tlc.o

${TL_PARSER_OBJECTS}: ${OBJ}/%.o: ${srcdir}/tgl/tl-parser/%.c | create_dirs
	${CC} ${INCLUDE} ${COMPILE_FLAGS} -iquote ${srcdir}/tgl/tl-parser -c -MP -MD -MF ${DEP}/$*.d -MQ ${OBJ}/$*.o -o $@ $<

${EXE}/tl-parser: ${TL_PARSER_OBJECTS}
	${CC} $^ ${LINK_FLAGS} -o $@
